import { useEffect, useState } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar, Line, Doughnut } from 'react-chartjs-2';
import {
  analyticsSummary,
  analyticsMostBorrowed,
  analyticsCategoryBorrowing,
  analyticsMonthlyTrend,
  analyticsOverdue,
  analyticsEtlRuns,
  errorMessage,
} from '../api.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  ArcElement,
  Title,
  Tooltip,
  Legend
);

const CHART_PALETTE = [
  '#2563eb', '#16a34a', '#d97706', '#dc2626', '#7c3aed',
  '#0891b2', '#db2777', '#65a30d', '#ea580c', '#0ea5e9',
];

export default function Analytics() {
  const [summary, setSummary] = useState(null);
  const [topBooks, setTopBooks] = useState([]);
  const [byCategory, setByCategory] = useState([]);
  const [trend, setTrend] = useState([]);
  const [overdue, setOverdue] = useState([]);
  const [etlRuns, setEtlRuns] = useState([]);
  const [onlyOpen, setOnlyOpen] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  async function loadAll(openOnly) {
    try {
      setLoading(true);
      setError('');
      const [s, mb, cb, mt, od, runs] = await Promise.all([
        analyticsSummary(),
        analyticsMostBorrowed(10),
        analyticsCategoryBorrowing(),
        analyticsMonthlyTrend(),
        analyticsOverdue(openOnly),
        analyticsEtlRuns(),
      ]);
      setSummary(s);
      setTopBooks(mb);
      setByCategory(cb);
      setTrend(mt);
      setOverdue(od);
      setEtlRuns(runs);
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadAll(onlyOpen); /* eslint-disable-next-line */ }, []);

  function refresh() { loadAll(onlyOpen); }
  function toggleOnlyOpen() {
    const next = !onlyOpen;
    setOnlyOpen(next);
    loadAll(next);
  }

  // ------- Chart datasets -------
  const mostBorrowedData = {
    labels: topBooks.map((b) => b.title.length > 32 ? b.title.slice(0, 30) + '...' : b.title),
    datasets: [
      {
        label: 'Borrow count',
        data: topBooks.map((b) => b.borrow_count),
        backgroundColor: CHART_PALETTE[0],
        borderRadius: 4,
      },
    ],
  };

  const categoryData = {
    labels: byCategory.map((c) => c.category),
    datasets: [
      {
        label: 'Borrows',
        data: byCategory.map((c) => c.borrow_count),
        backgroundColor: byCategory.map((_, i) => CHART_PALETTE[i % CHART_PALETTE.length]),
        borderWidth: 0,
      },
    ],
  };

  const monthlyData = {
    labels: trend.map((m) => m.month),
    datasets: [
      {
        label: 'Borrows / month',
        data: trend.map((m) => m.borrow_count),
        borderColor: CHART_PALETTE[2],
        backgroundColor: 'rgba(217,119,6,0.15)',
        fill: true,
        tension: 0.3,
        pointRadius: 4,
      },
    ],
  };

  const horizontalBarOpts = {
    indexAxis: 'y',
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: { x: { beginAtZero: true, ticks: { precision: 0 } } },
  };

  const doughnutOpts = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { position: 'right' } },
  };

  const lineOpts = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: { y: { beginAtZero: true, ticks: { precision: 0 } } },
  };

  return (
    <>
      <div className="page-header">
        <div>
          <h1>Analytics</h1>
          <div className="page-subtitle">
            Insights generated by the ETL pipeline (etl/run_etl.py)
          </div>
        </div>
        <button className="btn btn-secondary" onClick={refresh} disabled={loading}>
          {loading ? 'Refreshing...' : 'Refresh'}
        </button>
      </div>

      {error && <div className="alert">{error}</div>}

      {loading ? (
        <div className="loading">Loading analytics...</div>
      ) : (
        <>
          {/* ---------- KPI tiles ---------- */}
          <div className="stat-grid">
            <StatCard label="Total Borrows" value={summary?.total_borrows ?? 0} accent="blue" />
            <StatCard label="Unique Books Borrowed" value={summary?.unique_books_borrowed ?? 0} accent="green" />
            <StatCard label="Overdue (all)" value={summary?.overdue_total ?? 0} accent="amber" />
            <StatCard label="Overdue (open)" value={summary?.overdue_open ?? 0} accent="purple" />
          </div>

          {summary?.top_book && summary?.top_category && (
            <div className="card highlight-card">
              <div className="highlight-row">
                <div>
                  <div className="highlight-label">Top book</div>
                  <div className="highlight-value">{summary.top_book.title}</div>
                  <div className="highlight-sub">{summary.top_book.borrow_count} borrows</div>
                </div>
                <div>
                  <div className="highlight-label">Top category</div>
                  <div className="highlight-value">{summary.top_category.category}</div>
                  <div className="highlight-sub">{summary.top_category.borrow_count} borrows</div>
                </div>
              </div>
            </div>
          )}

          {/* ---------- Charts ---------- */}
          <div className="chart-grid">
            <div className="card chart-card">
              <h2>Most borrowed books (top 10)</h2>
              <div className="chart-canvas chart-tall">
                <Bar data={mostBorrowedData} options={horizontalBarOpts} />
              </div>
            </div>

            <div className="card chart-card">
              <h2>Borrowing by category</h2>
              <div className="chart-canvas">
                <Doughnut data={categoryData} options={doughnutOpts} />
              </div>
            </div>

            <div className="card chart-card chart-wide">
              <h2>Monthly borrowing trend</h2>
              <div className="chart-canvas">
                <Line data={monthlyData} options={lineOpts} />
              </div>
            </div>
          </div>

          {/* ---------- Overdue table ---------- */}
          <div className="card">
            <div className="card-header">
              <h2>Overdue transactions</h2>
              <label className="toggle">
                <input type="checkbox" checked={onlyOpen} onChange={toggleOnlyOpen} />
                Only still-open loans
              </label>
            </div>
            {overdue.length === 0 ? (
              <div className="empty">
                <div className="empty-title">No overdue transactions</div>
              </div>
            ) : (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Book</th>
                      <th>Borrower</th>
                      <th>Borrowed</th>
                      <th>Returned</th>
                      <th>Loan days</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {overdue.slice(0, 50).map((t) => (
                      <tr key={t.transaction_id}>
                        <td>{t.transaction_id}</td>
                        <td>{t.title}</td>
                        <td>{t.borrower_name}</td>
                        <td>{new Date(t.borrow_date).toLocaleDateString()}</td>
                        <td>{t.return_date ? new Date(t.return_date).toLocaleDateString() : '-'}</td>
                        <td>{Math.round(t.loan_days)}</td>
                        <td>
                          {t.is_returned ? (
                            <span className="pill pill-returned">Returned late</span>
                          ) : (
                            <span className="pill pill-borrowed">Still open</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {overdue.length > 50 && (
                  <div className="table-footnote">
                    Showing first 50 of {overdue.length} overdue rows.
                  </div>
                )}
              </div>
            )}
          </div>

          {/* ---------- ETL run audit ---------- */}
          <div className="card">
            <h2>ETL run history</h2>
            {etlRuns.length === 0 ? (
              <div className="empty">
                <div className="empty-title">No ETL runs recorded yet</div>
                <div>
                  Run <code>python -m etl.run_etl</code> to populate the analytics tables.
                </div>
              </div>
            ) : (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>Run</th>
                      <th>When</th>
                      <th>Raw books</th>
                      <th>Raw borrowers</th>
                      <th>Raw transactions</th>
                      <th>Clean books</th>
                      <th>Clean borrowers</th>
                      <th>Clean transactions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {etlRuns.map((r) => (
                      <tr key={r.run_id}>
                        <td>{r.run_id}</td>
                        <td>{new Date(r.run_at).toLocaleString()}</td>
                        <td>{r.raw_books}</td>
                        <td>{r.raw_borrowers}</td>
                        <td>{r.raw_transactions}</td>
                        <td>{r.clean_books}</td>
                        <td>{r.clean_borrowers}</td>
                        <td>{r.clean_transactions}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}
    </>
  );
}

function StatCard({ label, value, accent }) {
  return (
    <div className={`stat-card stat-accent-${accent}`}>
      <div className="stat-label">{label}</div>
      <div className="stat-value">{value}</div>
    </div>
  );
}
